# Generated by Django 6.1 on 2026-08-08 07:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
                ('source', models.CharField(choices=[('Manual', 'Manual'), ('CSV Import', 'CSV Import'), ('Google', 'Google'), ('Other', 'Other')], default='Manual', max_length=50)),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('status', models.CharField(choices=[('Unanalyzed', 'Unanalyzed'), ('Analyzed', 'Analyzed')], default='Unanalyzed', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('is_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reply', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('positive_aspects', models.JSONField(blank=True, default=list)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='reviews.review')),
            ],
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['business', 'created_at'], name='reviews_rev_busines_c9d187_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['business', 'sentiment'], name='reviews_rev_busines_378949_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['business', 'status'], name='reviews_rev_busines_d642f9_idx'),
        ),
    ]
