# Generated by Django 6.1 on 2026-08-08 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Restaurant', 'Restaurant'), ('Hotel', 'Hotel'), ('E-commerce', 'E-commerce'), ('Retail', 'Retail'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Services', 'Services'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('tone', models.CharField(choices=[('Professional', 'Professional'), ('Friendly', 'Friendly'), ('Warm', 'Warm'), ('Formal', 'Formal'), ('Casual', 'Casual')], default='Professional', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
